language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
script:
# Test
- mvn -Dtest=**/*Test test
# Integration Test
- if [ $TRAVIS_TEST_RESULT == 0 ];
     then  mvn -Dtest=**/*IT package; 
     else  echo "ERRORES!!! ... se abortan resto de test"; 
  fi
# Functional Testing
- if [ $TRAVIS_TEST_RESULT == 0 ];
     then  mvn -Dtest=**/*FunctionalTesting verify;
     else  echo "ERRORES!!! ... se abortan resto de test"; 
  fi
